version: "3.3"

services:
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: "ingresso"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "caelum"
      # You can use whatever password you like
      MYSQL_PASSWORD: "root"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - ingresso-db:/var/lib/mysql
# Names our volume
volumes:
  ingresso-db:
